@host = http://localhost:3000


GET http://localhost:3000/api/autores

### Recuperar autores
GET {{host}}/api/autores

### Recuperar posts
GET {{host}}/api/posts

### Crear un nuevo autor
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "FEDERICO",
    "email": "federico@email.com",
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv2z4qC1hGu8IOWbmE_a-7wWGMa_1Xq3n1HgrGHVNWLIe1OgvnK6klkBhvK1YGdMUP9_I&usqp=CAU"
}

### Crear un nuevo post
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "Cultiva tus fresas",
    "descripcion": "Manual de cultivo de fresas de temporada",
    "fecha_creacion": "2024-06-09",
    "categoria": "OCIO",
    "autores_id": 1
}

### Recuperar posts por autor concreto
GET {{host}}/api/posts?autor=CRISTINA