@host = http://localhost:3000


### Recuperar autores
GET {{host}}/api/autores

### Recuperar posts
GET {{host}}/api/posts

### Recuperar posts por autor concreto
GET {{host}}/api/posts?autor=1

### Crear un nuevo autor
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "RAFAEL",
    "email": "rafael@email.com",
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv2z4qC1hGu8IOWbmE_a-7wWGMa_1Xq3n1HgrGHVNWLIe1OgvnK6klkBhvK1YGdMUP9_I&usqp=CAU"
}

### Crear un nuevo post
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "Express test",
    "descripcion": "Desarrolla tu aplicación Express en un santiamén",
    "fecha_creacion": "2025-02-07",
    "categoria": "EDUCACIÓN",
    "autores_id": 1
}
